#!/bin/sh

### BEGIN INIT INFO
# Provides: eye
# Required-Start: $all
# Required-Stop: $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: eye daemon, providing process monitoring
# Description: eye is a monitoring tool. More info at https://github.com/kostya/eye
### END INIT INFO

#PATH="/usr/local/bin:/home/arisi/.rbenv/shims:/home/arisi/.rbenv/bin::$PATH"
export HOME="/home/pi"
EYE_BIN=`which eye`
test -x $EYE_BIN || { echo "$EYE_BIN not installed";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

EYE_CONFIG=/etc/eye/eye.rb
test -r $EYE_CONFIG || { echo "$EYE_CONFIG not existing";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 6; fi; }

case "$1" in
  start)
    echo "Starting eye "
    sudo -u pi $EYE_BIN load $EYE_CONFIG
    ;;
  stop)
    echo "Shutting down eye "
    sudo -u pi $EYE_BIN stop '*'
    sudo -u pi $EYE_BIN quit
    ;;
  reload)
    echo "Reloadind eye "
    sudo -u pi $EYE_BIN delete '*'		
    sudo -u pi $EYE_BIN load $EYE_CONFIG		
    sudo -u pi $EYE_BIN restart '*'
    sudo -u pi $EYE_BIN info
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    sudo -u pi $EYE_BIN info
  ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
    ;;
esac
